---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-velero
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/velero
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-backup-storage-location
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-velero
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/backup-storage-location
  prune: true
  patches:
    - target:
        kind: BackupStorageLocation
        name: infomaniak
      patch: |-
        - op: add
          path: /spec/objectStorage/prefix
          value: "tractor-k8s-shared"
        - op: add
          path: /spec/config/s3Url
          value: "https://s3.pub2.infomaniak.cloud/"
        - op: add
          path: /spec/config/publicUrl
          value: "https://s3.pub2.infomaniak.cloud/object/v1/AUTH_b2f67cfc61224da6b87153025cb404e6/k8s-backup"

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-backup-schedule
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-backup-storage-location
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/backup-schedule
  prune: true
