---
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: infomaniak
  namespace: velero
spec:
  accessMode: ReadWrite
  default: true
  objectStorage:
    bucket: tractor-k8s-backup
  config:
    s3ForcePathStyle: "true"
  provider: velero.io/aws
  credential:
    key: tractor-k8s-backup
    name: infomaniak-s3-credentials
