---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: clever-debug
  namespace: clever-debug
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: clever-debug-webhook-receiver-token
  resources:
    - kind: GitRepository
      name: clever-debug
