apiVersion: v1
kind: Secret
metadata:
  name: velero-credentials
  namespace: velero
type: Opaque
#stringData:
#  clouds.yaml: |
#    clouds:
#      infomaniak:
#        region_name: "dc4-a"
#        auth:
#          auth_url: "https://api.pub1.infomaniak.cloud/identity"
#          application_credential_name: "tractor-k8s-shared-velero"
#          application_credential_id: ""
#          application_credential_secret: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: os-swift-config
  namespace: velero
type: Opaque
#stringData:
#  OS_SWIFT_ENDPOINT_OVERRIDE: https://s3.pub2.infomaniak.cloud/object/v1/AUTH_<secret>/
