#
# RBAC
#
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: pbs-who-is-who
  
  annotations:
    "tractor.scout.ch/instance-pool": pck-2tvwejg-pne
  
  name: pbs-who-is-who
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: pbs-who-is-who
  name: pbs-who-is-who
  namespace: pbs-who-is-who
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: pbs-who-is-who
  name: gotk-reconciler
  namespace: pbs-who-is-who
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: pbs-who-is-who
    namespace: pbs-who-is-who

#
# Sync
#
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: pbs-who-is-who
  namespace: pbs-who-is-who
spec:
  interval: 1h
  ref:
    branch: main
  secretRef:
    name: flux-git-deploy-key
  url: ssh://git@github.com/scout-ch/tractor-k8s-shared-pbs-who-is-who.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pbs-who-is-who
  namespace: pbs-who-is-who
spec:
  serviceAccountName: pbs-who-is-who
  interval: 10m0s
  path: .
  prune: true
  sourceRef:
    kind: GitRepository
    name: pbs-who-is-who
